# Data Preprocessing

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv('SBAnational.csv', header=0, encoding='latin1')
df.head()

,LoanNr_ChkDgt,Name,City,State,Zip,Bank,BankState,NAICS,ApprovalDate,ApprovalFY,...,RevLineCr,LowDoc,ChgOffDate,DisbursementDate,DisbursementGross,BalanceGross,MIS_Status,ChgOffPrinGr,GrAppv,SBA_Appv
0,1000014003,ABC HOBBYCRAFT,EVANSVILLE,IN,47711.0,FIFTH THIRD BANK,OH,451120.0,28-Feb-97,1997.0,...,N,Y,NaN,28-Feb-99,"$60,000.00",$0.00,P I F,$0.00,"$60,000.00","$48,000.00"
1,1000024006,LANDMARK BAR & GRILLE (THE),NEW PARIS,IN,46526.0,1ST SOURCE BANK,IN,722410.0,28-Feb-97,1997.0,...,N,Y,NaN,31-May-97,"$40,000.00",$0.00,P I F,$0.00,"$40,000.00","$32,000.00"
2,1000034009,"WHITLOCK DDS, TODD M.",BLOOMINGTON,IN,47401.0,GRANT COUNTY STATE BANK,IN,621210.0,28-Feb-97,1997.0,...,N,N,NaN,31-Dec-97,"$287,000.00",$0.00,P I F,$0.00,"$287,000.00","$215,250.00"
3,1000044001,"BIG BUCKS PAWN & JEWELRY, LLC",BROKEN ARROW,OK,74012.0,1ST NATL BK & TR CO OF BROKEN,OK,0.0,28-Feb-97,1997.0,...,N,Y,NaN,30-Jun-97,"$35,000.00",$0.00,P I F,$0.00,"$35,000.00","$28,000.00"
4,1000054004,"ANASTASIA CONFECTIONS, INC.",ORLANDO,FL,32801.0,FLORIDA BUS. DEVEL CORP,FL,0.0,28-Feb-97,1997.0,...,N,N,NaN,14-May-97,"$229,000.00",$0.00,P I F,$0.00,"$229,000.00","$229,000.00"

In [ ]:
df.shape

(72616, 27)

In [ ]:
df.isnull().sum()

LoanNr_ChkDgt            0
Name                     5
City                     1
State                    3
Zip                      1
Bank                    75
BankState               75
NAICS                    1
ApprovalDate             1
ApprovalFY               1
Term                     1
NoEmp                    1
NewExist                 1
CreateJob                1
RetainedJob              1
FranchiseCode            1
UrbanRural               1
RevLineCr               11
LowDoc                   1
ChgOffDate           54654
DisbursementDate       108
DisbursementGross        1
BalanceGross             1
MIS_Status             615
ChgOffPrinGr             1
GrAppv                   1
SBA_Appv                 1
dtype: int64

In [ ]:
num_duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {num_duplicates}")

Number of duplicate rows: 0

In [ ]:
cols_to_drop = ['ChgOffDate', 'ApprovalDate', 'LoanNr_ChkDgt', 'Name']
df = df.drop(columns=cols_to_drop, errors='ignore')
df.head()

,City,State,Zip,Bank,BankState,NAICS,ApprovalFY,Term,NoEmp,NewExist,...,UrbanRural,RevLineCr,LowDoc,DisbursementDate,DisbursementGross,BalanceGross,MIS_Status,ChgOffPrinGr,GrAppv,SBA_Appv
0,EVANSVILLE,IN,47711.0,FIFTH THIRD BANK,OH,451120.0,1997.0,84.0,4.0,2.0,...,0.0,N,Y,28-Feb-99,"$60,000.00",$0.00,P I F,$0.00,"$60,000.00","$48,000.00"
1,NEW PARIS,IN,46526.0,1ST SOURCE BANK,IN,722410.0,1997.0,60.0,2.0,2.0,...,0.0,N,Y,31-May-97,"$40,000.00",$0.00,P I F,$0.00,"$40,000.00","$32,000.00"
2,BLOOMINGTON,IN,47401.0,GRANT COUNTY STATE BANK,IN,621210.0,1997.0,180.0,7.0,1.0,...,0.0,N,N,31-Dec-97,"$287,000.00",$0.00,P I F,$0.00,"$287,000.00","$215,250.00"
3,BROKEN ARROW,OK,74012.0,1ST NATL BK & TR CO OF BROKEN,OK,0.0,1997.0,60.0,2.0,1.0,...,0.0,N,Y,30-Jun-97,"$35,000.00",$0.00,P I F,$0.00,"$35,000.00","$28,000.00"
4,ORLANDO,FL,32801.0,FLORIDA BUS. DEVEL CORP,FL,0.0,1997.0,240.0,14.0,1.0,...,0.0,N,N,14-May-97,"$229,000.00",$0.00,P I F,$0.00,"$229,000.00","$229,000.00"

In [ ]:
#To prevent data leakage we need to drop several columns
data_leak_cols = ['DisbursementDate', 'ChgOffPrinGr', 'BalanceGross', 'DisbursementGross']
df = df.drop(columns=data_leak_cols, errors='ignore')
df.head()

,City,State,Zip,Bank,BankState,NAICS,ApprovalFY,Term,NoEmp,NewExist,CreateJob,RetainedJob,FranchiseCode,UrbanRural,RevLineCr,LowDoc,MIS_Status,GrAppv,SBA_Appv
0,EVANSVILLE,IN,47711.0,FIFTH THIRD BANK,OH,451120.0,1997.0,84.0,4.0,2.0,0.0,0.0,1.0,0.0,N,Y,P I F,"$60,000.00","$48,000.00"
1,NEW PARIS,IN,46526.0,1ST SOURCE BANK,IN,722410.0,1997.0,60.0,2.0,2.0,0.0,0.0,1.0,0.0,N,Y,P I F,"$40,000.00","$32,000.00"
2,BLOOMINGTON,IN,47401.0,GRANT COUNTY STATE BANK,IN,621210.0,1997.0,180.0,7.0,1.0,0.0,0.0,1.0,0.0,N,N,P I F,"$287,000.00","$215,250.00"
3,BROKEN ARROW,OK,74012.0,1ST NATL BK & TR CO OF BROKEN,OK,0.0,1997.0,60.0,2.0,1.0,0.0,0.0,1.0,0.0,N,Y,P I F,"$35,000.00","$28,000.00"
4,ORLANDO,FL,32801.0,FLORIDA BUS. DEVEL CORP,FL,0.0,1997.0,240.0,14.0,1.0,7.0,7.0,1.0,0.0,N,N,P I F,"$229,000.00","$229,000.00"

In [ ]:
money_columns = ['GrAppv', 'SBA_Appv']
for col in money_columns:
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace('$', '', regex=False)
    df[col] = df[col].str.replace(',', '', regex=False)
    df[col] = pd.to_numeric(df[col], errors='coerce')
df.head()

,City,State,Zip,Bank,BankState,NAICS,ApprovalFY,Term,NoEmp,NewExist,CreateJob,RetainedJob,FranchiseCode,UrbanRural,RevLineCr,LowDoc,MIS_Status,GrAppv,SBA_Appv
0,EVANSVILLE,IN,47711.0,FIFTH THIRD BANK,OH,451120.0,1997.0,84.0,4.0,2.0,0.0,0.0,1.0,0.0,N,Y,P I F,60000.0,48000.0
1,NEW PARIS,IN,46526.0,1ST SOURCE BANK,IN,722410.0,1997.0,60.0,2.0,2.0,0.0,0.0,1.0,0.0,N,Y,P I F,40000.0,32000.0
2,BLOOMINGTON,IN,47401.0,GRANT COUNTY STATE BANK,IN,621210.0,1997.0,180.0,7.0,1.0,0.0,0.0,1.0,0.0,N,N,P I F,287000.0,215250.0
3,BROKEN ARROW,OK,74012.0,1ST NATL BK & TR CO OF BROKEN,OK,0.0,1997.0,60.0,2.0,1.0,0.0,0.0,1.0,0.0,N,Y,P I F,35000.0,28000.0
4,ORLANDO,FL,32801.0,FLORIDA BUS. DEVEL CORP,FL,0.0,1997.0,240.0,14.0,1.0,7.0,7.0,1.0,0.0,N,N,P I F,229000.0,229000.0

In [ ]:
print(df.dtypes)

City              object
State             object
Zip              float64
Bank              object
BankState         object
NAICS            float64
ApprovalFY       float64
Term             float64
NoEmp            float64
NewExist         float64
CreateJob        float64
RetainedJob      float64
FranchiseCode    float64
UrbanRural       float64
RevLineCr         object
LowDoc            object
MIS_Status        object
GrAppv           float64
SBA_Appv         float64
dtype: object

In [ ]:
#Change the zip code to a string format and make sure that there are five numbers in the code
df['Zip'] = df['Zip'].astype(str).str.zfill(5)
#Change the approval fiscal year into a numeric value, but remove the A in the values
#The 'A' is because of a change in how fiscal year is filed, but for our case it won't matter too much so we just treat it as the same year
df['ApprovalFY'] = df['ApprovalFY'].astype(str).str.replace('A', '', regex=False)
df['ApprovalFY'] = pd.to_numeric(df['ApprovalFY'], errors='coerce')
#NewExist needs to be changed into categorical data and one-hot encoding will be applied later
df['NewExist'] = df['NewExist'].map({1: 'Existing Business', 2: 'New Business'})
df['NewExist'] = df['NewExist'].fillna('Unknown')
#Change the Franchise code into a boolean
df['IsFranchise'] = (df['FranchiseCode'] > 1).astype(int)
df = df.drop(columns='FranchiseCode', errors='ignore')
#UrbanRural is categorical, change it into a category so one-hot encoding can be performed later
df['UrbanRural'] = df['UrbanRural'].map({1: 'Urban', 2: 'Rural', 0: 'Undefined'})
#Change RevLineCr into categorical
df['RevLineCr'] = df['RevLineCr'].map({'Y': 'Yes', 'N': 'No'})
df['RevLineCr'] = df['RevLineCr'].fillna('Unknown')
#Change LowDoc into categorical
df['LowDoc'] = df['LowDoc'].map({'Y': 'Yes', 'N': 'No'})
df['LowDoc'] = df['LowDoc'].fillna('Unknown')
#Have to change our target feature into binary format for easier classification
df['MIS_Status'] = df['MIS_Status'].map({'P I F': 0, 'CHGOFF': 1})
# Converting the NAICS codes to their corresponding industries (based on first two digits)
df['Industry_Code'] = df['NAICS'].astype(str).str[:2]
industry_map = {
    '11': 'Agriculture/Forestry/Fishing/Hunting', '21': 'Mining/Quarrying/Oil & Gas Extraction', '22': 'Utilities', '23': 'Construction',
    '31': 'Manufacturing', '32': 'Manufacturing', '33': 'Manufacturing',
    '42': 'Wholesale Trade', '44': 'Retail Trade', '45': 'Retail Trade', '48': 'Transportation/Warehousing', '49': 'Transportation/Warehousing',
    '51': 'Information', '52': 'Finance/Insurance', '53': 'Real Estate', '54': 'Professional/Scientific/Tech Services',
    '55': 'Management', '56': 'Admin/Support/Waste Management', '61': 'Educational', '62': 'Health Care',
    '71': 'Arts/Entertainment', '72': 'Accomodations/Food', '81': 'Other Services', '92': 'Public Admin'
}
df['Industry'] = df['Industry_Code'].map(industry_map).fillna('Other/Unknown')
df = df.drop(columns=['NAICS', 'Industry_Code'], errors='ignore')
df.head()

,City,State,Zip,Bank,BankState,ApprovalFY,Term,NoEmp,NewExist,CreateJob,RetainedJob,UrbanRural,RevLineCr,LowDoc,MIS_Status,GrAppv,SBA_Appv,IsFranchise,Industry
0,EVANSVILLE,IN,47711.0,FIFTH THIRD BANK,OH,1997.0,84.0,4.0,New Business,0.0,0.0,Undefined,No,Yes,0.0,60000.0,48000.0,0,Retail Trade
1,NEW PARIS,IN,46526.0,1ST SOURCE BANK,IN,1997.0,60.0,2.0,New Business,0.0,0.0,Undefined,No,Yes,0.0,40000.0,32000.0,0,Accomodations/Food
2,BLOOMINGTON,IN,47401.0,GRANT COUNTY STATE BANK,IN,1997.0,180.0,7.0,Existing Business,0.0,0.0,Undefined,No,No,0.0,287000.0,215250.0,0,Health Care
3,BROKEN ARROW,OK,74012.0,1ST NATL BK & TR CO OF BROKEN,OK,1997.0,60.0,2.0,Existing Business,0.0,0.0,Undefined,No,Yes,0.0,35000.0,28000.0,0,Other/Unknown
4,ORLANDO,FL,32801.0,FLORIDA BUS. DEVEL CORP,FL,1997.0,240.0,14.0,Existing Business,7.0,7.0,Undefined,No,No,0.0,229000.0,229000.0,0,Other/Unknown

In [ ]:
print(df.dtypes)

City            object
State           object
Zip             object
Bank            object
BankState       object
ApprovalFY     float64
Term           float64
NoEmp          float64
NewExist        object
CreateJob      float64
RetainedJob    float64
UrbanRural      object
RevLineCr       object
LowDoc          object
MIS_Status     float64
GrAppv         float64
SBA_Appv       float64
IsFranchise      int64
Industry        object
dtype: object

In [ ]:
df = df.dropna(subset=['MIS_Status'])
df.isnull().sum()

City            1
State           1
Zip             0
Bank           48
BankState      48
ApprovalFY      0
Term            0
NoEmp           0
NewExist        0
CreateJob       0
RetainedJob     0
UrbanRural      0
RevLineCr       0
LowDoc          0
MIS_Status      0
GrAppv          0
SBA_Appv        0
IsFranchise     0
Industry        0
dtype: int64

In [ ]:
#Just make all of these na values unknown, they will not be in our model anyways they are only for visualizations
df['City'] = df['City'].fillna('Unknown')
df['State'] = df['State'].fillna('Unknown')
df['Bank'] = df['Bank'].fillna('Unknown')
df['BankState'] = df['BankState'].fillna('Unknown')
df.isnull().sum()

City           0
State          0
Zip            0
Bank           0
BankState      0
ApprovalFY     0
Term           0
NoEmp          0
NewExist       0
CreateJob      0
RetainedJob    0
UrbanRural     0
RevLineCr      0
LowDoc         0
MIS_Status     0
GrAppv         0
SBA_Appv       0
IsFranchise    0
Industry       0
dtype: int64

In [ ]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Define feature groups
categorical_cols = ['NewExist', 'UrbanRural', 'RevLineCr', 'LowDoc', 'Industry']
numeric_cols = ['Term', 'NoEmp', 'CreateJob', 'RetainedJob', 'GrAppv', 'SBA_Appv']

# 1. Build the preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        # Scaling the numeric features
        ('num', StandardScaler(), numeric_cols),
        # Encoding the categorical features (sparse_output=False is key)
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_cols)
    ],
    remainder='passthrough',
    verbose_feature_names_out=False
)

# 2. Use the "pandas" output style to prevent the "All Zeros" confusion
preprocessor.set_output(transform="pandas")

# 3. Transform the data
df_cleaned = preprocessor.fit_transform(df)

# 4. Restore original types for non-scaled columns
# This prevents your IDs/Years from being floats
type_mapping = {
    'City': 'object', 'State': 'object', 'Zip': 'object',
    'Bank': 'object', 'BankState': 'object',
    'ApprovalFY': 'int64', 'IsFranchise': 'int64'
}
df_cleaned = df_cleaned.astype({k: v for k, v in type_mapping.items() if k in df_cleaned.columns})

# 5. Fix the "Visual" problem: Reorder columns
# This puts your recognizable text columns back at the front
other_cols = [c for c in df_cleaned.columns if c not in numeric_cols and not c.startswith(tuple(categorical_cols))]
column_order = other_cols + numeric_cols + [c for c in df_cleaned.columns if c not in other_cols + numeric_cols]

df_cleaned = df_cleaned[column_order]

display(df_cleaned.head())

,City,State,Zip,Bank,BankState,ApprovalFY,MIS_Status,IsFranchise,Term,NoEmp,...,Industry_Mining/Quarrying/Oil & Gas Extraction,Industry_Other Services,Industry_Other/Unknown,Industry_Professional/Scientific/Tech Services,Industry_Public Admin,Industry_Real Estate,Industry_Retail Trade,Industry_Transportation/Warehousing,Industry_Utilities,Industry_Wholesale Trade
0,EVANSVILLE,IN,47711.0,FIFTH THIRD BANK,OH,1997,0.0,0,-0.095118,-0.070299,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,NEW PARIS,IN,46526.0,1ST SOURCE BANK,IN,1997,0.0,0,-0.455065,-0.100950,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,BLOOMINGTON,IN,47401.0,GRANT COUNTY STATE BANK,IN,1997,0.0,0,1.344670,-0.024324,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,BROKEN ARROW,OK,74012.0,1ST NATL BK & TR CO OF BROKEN,OK,1997,0.0,0,-0.455065,-0.100950,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ORLANDO,FL,32801.0,FLORIDA BUS. DEVEL CORP,FL,1997,0.0,0,2.244538,0.082953,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df_cleaned.dtypes

City                                               object
State                                              object
Zip                                                object
Bank                                               object
BankState                                          object
ApprovalFY                                          int64
MIS_Status                                        float64
IsFranchise                                         int64
Term                                              float64
NoEmp                                             float64
CreateJob                                         float64
RetainedJob                                       float64
GrAppv                                            float64
SBA_Appv                                          float64
NewExist_Existing Business                        float64
NewExist_New Business                             float64
NewExist_Unknown                                  float64
UrbanRural_Rural                                  float64
UrbanRural_Undefined                              float64
UrbanRural_Urban                                  float64
RevLineCr_No                                      float64
RevLineCr_Unknown                                 float64
RevLineCr_Yes                                     float64
LowDoc_No                                         float64
LowDoc_Unknown                                    float64
LowDoc_Yes                                        float64
Industry_Accomodations/Food                       float64
Industry_Admin/Support/Waste Management           float64
Industry_Agriculture/Forestry/Fishing/Hunting     float64
Industry_Arts/Entertainment                       float64
Industry_Construction                             float64
Industry_Educational                              float64
Industry_Finance/Insurance                        float64
Industry_Health Care                              float64
Industry_Information                              float64
Industry_Management                               float64
Industry_Manufacturing                            float64
Industry_Mining/Quarrying/Oil & Gas Extraction    float64
Industry_Other Services                           float64
Industry_Other/Unknown                            float64
Industry_Professional/Scientific/Tech Services    float64
Industry_Public Admin                             float64
Industry_Real Estate                              float64
Industry_Retail Trade                             float64
Industry_Transportation/Warehousing               float64
Industry_Utilities                                float64
Industry_Wholesale Trade                          float64
dtype: object

In [ ]:
df_cleaned.columns

Index(['City', 'State', 'Zip', 'Bank', 'BankState', 'ApprovalFY', 'MIS_Status',
       'IsFranchise', 'Term', 'NoEmp', 'CreateJob', 'RetainedJob', 'GrAppv',
       'SBA_Appv', 'NewExist_Existing Business', 'NewExist_New Business',
       'NewExist_Unknown', 'UrbanRural_Rural', 'UrbanRural_Undefined',
       'UrbanRural_Urban', 'RevLineCr_No', 'RevLineCr_Unknown',
       'RevLineCr_Yes', 'LowDoc_No', 'LowDoc_Unknown', 'LowDoc_Yes',
       'Industry_Accomodations/Food',
       'Industry_Admin/Support/Waste Management',
       'Industry_Agriculture/Forestry/Fishing/Hunting',
       'Industry_Arts/Entertainment', 'Industry_Construction',
       'Industry_Educational', 'Industry_Finance/Insurance',
       'Industry_Health Care', 'Industry_Information', 'Industry_Management',
       'Industry_Manufacturing',
       'Industry_Mining/Quarrying/Oil & Gas Extraction',
       'Industry_Other Services', 'Industry_Other/Unknown',
       'Industry_Professional/Scientific/Tech Services',
       'Industry_Public Admin', 'Industry_Real Estate',
       'Industry_Retail Trade', 'Industry_Transportation/Warehousing',
       'Industry_Utilities', 'Industry_Wholesale Trade'],
      dtype='object')

In [ ]:
df_cleaned.isnull().sum()

City                                              0
State                                             0
Zip                                               0
Bank                                              0
BankState                                         0
ApprovalFY                                        0
MIS_Status                                        0
IsFranchise                                       0
Term                                              0
NoEmp                                             0
CreateJob                                         0
RetainedJob                                       0
GrAppv                                            0
SBA_Appv                                          0
NewExist_Existing Business                        0
NewExist_New Business                             0
NewExist_Unknown                                  0
UrbanRural_Rural                                  0
UrbanRural_Undefined                              0
UrbanRural_Urban                                  0
RevLineCr_No                                      0
RevLineCr_Unknown                                 0
RevLineCr_Yes                                     0
LowDoc_No                                         0
LowDoc_Unknown                                    0
LowDoc_Yes                                        0
Industry_Accomodations/Food                       0
Industry_Admin/Support/Waste Management           0
Industry_Agriculture/Forestry/Fishing/Hunting     0
Industry_Arts/Entertainment                       0
Industry_Construction                             0
Industry_Educational                              0
Industry_Finance/Insurance                        0
Industry_Health Care                              0
Industry_Information                              0
Industry_Management                               0
Industry_Manufacturing                            0
Industry_Mining/Quarrying/Oil & Gas Extraction    0
Industry_Other Services                           0
Industry_Other/Unknown                            0
Industry_Professional/Scientific/Tech Services    0
Industry_Public Admin                             0
Industry_Real Estate                              0
Industry_Retail Trade                             0
Industry_Transportation/Warehousing               0
Industry_Utilities                                0
Industry_Wholesale Trade                          0
dtype: int64

In [ ]:
#Now export our cleaned work into a new cleaned csv file
df_cleaned.to_csv('SBAnational_cleaned.csv', index=False)